package patmob.patbase.monitor;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import org.json.JSONObject;

/**
 *
 * @author NM54935
 */
public class MonitorFrame_1 extends javax.swing.JFrame {
    PatbaseMonitorPlugin plugin;
    TableModel tableModel;
    MonitorFilterViewer filterViewer;

    /**
     * Creates new form MonitorFrame_1
     * @param pmp
     * @param model
     */
    public MonitorFrame_1(PatbaseMonitorPlugin pmp, TableModel model) {
        plugin = pmp;
        tableModel = model;
        initComponents();
        jTable1.getSelectionModel()
                .addListSelectionListener(new MonitorSelectionListener());
        filterViewer = new MonitorFilterViewer(
                newLegalStatusTextArea,
                newPublicationsTextArea,
                pairBulkDataTextArea,
                rawJsonTextArea);
    }
    
    private class MonitorSelectionListener implements ListSelectionListener {
        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (!e.getValueIsAdjusting()) {
                int viewRow = jTable1.getSelectedRow();
                if (viewRow>=0) {
                    int modelRow = jTable1.convertRowIndexToModel(viewRow);
                    JSONObject pbFam = plugin.monitorProject
                            .getJSONArray("Families").getJSONObject(modelRow);
                            pbFam.getString("Family");
                    JSONObject fullFamily = plugin.annotatedFamilies
                            .get(pbFam.getString("Family"));
                    if (fullFamily!=null) {
                        filterViewer.display(fullFamily);
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        displayTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        newPublicationsTextArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        newLegalStatusTextArea = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        pairBulkDataTextArea = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rawJsonTextArea = new javax.swing.JTextArea();
        setupTabbedPane = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        profilesPanel = new javax.swing.JPanel();
        anyDateRadioButton = new javax.swing.JRadioButton();
        defineDateRadioButton = new javax.swing.JRadioButton();
        fromDateTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        toDateTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        profileNameTextField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        worldwideRadioButton = new javax.swing.JRadioButton();
        definedCCsRadioButton = new javax.swing.JRadioButton();
        definedCCsTextField = new javax.swing.JTextField();
        runPLMonitorButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PatMOb: New Publications/Legal Status Monitor");

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        newPublicationsTextArea.setColumns(20);
        newPublicationsTextArea.setRows(5);
        jScrollPane2.setViewportView(newPublicationsTextArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );

        displayTabbedPane.addTab("New Publications", jPanel2);

        newLegalStatusTextArea.setColumns(20);
        newLegalStatusTextArea.setRows(5);
        jScrollPane3.setViewportView(newLegalStatusTextArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );

        displayTabbedPane.addTab("New Legal Status", jPanel3);

        pairBulkDataTextArea.setColumns(20);
        pairBulkDataTextArea.setRows(5);
        jScrollPane4.setViewportView(pairBulkDataTextArea);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );

        displayTabbedPane.addTab("PAIR Bulk Data Application Status", jPanel4);

        rawJsonTextArea.setColumns(20);
        rawJsonTextArea.setRows(5);
        jScrollPane1.setViewportView(rawJsonTextArea);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );

        displayTabbedPane.addTab("Raw JSON", jPanel7);

        jSplitPane1.setRightComponent(displayTabbedPane);

        jTable1.setModel(tableModel);
        jScrollPane5.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );

        setupTabbedPane.addTab("Monitor Table", jPanel5);

        buttonGroup1.add(anyDateRadioButton);
        anyDateRadioButton.setSelected(true);
        anyDateRadioButton.setText("Any date");
        anyDateRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anyDateRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(defineDateRadioButton);
        defineDateRadioButton.setText("From");
        defineDateRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defineDateRadioButtonActionPerformed(evt);
            }
        });

        fromDateTextField.setText("20161001");

        jLabel2.setText("to");

        toDateTextField.setText("20170115");

        jLabel1.setText("Profile Name");

        profileNameTextField.setText("Timmerbeil");

        buttonGroup2.add(worldwideRadioButton);
        worldwideRadioButton.setSelected(true);
        worldwideRadioButton.setText("Worldwide");
        worldwideRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                worldwideRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(definedCCsRadioButton);
        definedCCsRadioButton.setText("Defined CCs");
        definedCCsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                definedCCsRadioButtonActionPerformed(evt);
            }
        });

        definedCCsTextField.setText("US EP");

        javax.swing.GroupLayout profilesPanelLayout = new javax.swing.GroupLayout(profilesPanel);
        profilesPanel.setLayout(profilesPanelLayout);
        profilesPanelLayout.setHorizontalGroup(
            profilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(profilesPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profileNameTextField))
                    .addComponent(jSeparator2)
                    .addGroup(profilesPanelLayout.createSequentialGroup()
                        .addComponent(anyDateRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(defineDateRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fromDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 160, Short.MAX_VALUE))
                    .addGroup(profilesPanelLayout.createSequentialGroup()
                        .addComponent(worldwideRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(definedCCsRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(definedCCsTextField)))
                .addContainerGap())
        );
        profilesPanelLayout.setVerticalGroup(
            profilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(profileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(profilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(anyDateRadioButton)
                        .addComponent(defineDateRadioButton)
                        .addComponent(fromDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(worldwideRadioButton)
                    .addComponent(definedCCsRadioButton)
                    .addComponent(definedCCsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        setupTabbedPane.addTab("Profiles", profilesPanel);

        jSplitPane1.setLeftComponent(setupTabbedPane);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        runPLMonitorButton.setText("Run PL Monitor");
        runPLMonitorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runPLMonitorButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Load PatBase List...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(runPLMonitorButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(runPLMonitorButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //delete?
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void runPLMonitorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runPLMonitorButtonActionPerformed
        plugin.runAlert();
    }//GEN-LAST:event_runPLMonitorButtonActionPerformed

    private void worldwideRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_worldwideRadioButtonActionPerformed
        filterViewer.setDisplayedCCs("");
    }//GEN-LAST:event_worldwideRadioButtonActionPerformed

    private void definedCCsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_definedCCsRadioButtonActionPerformed
        filterViewer.setDisplayedCCs(definedCCsTextField.getText());
    }//GEN-LAST:event_definedCCsRadioButtonActionPerformed

    private void defineDateRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defineDateRadioButtonActionPerformed
        filterViewer.setDateFrom(fromDateTextField.getText());
        filterViewer.setDateTo(toDateTextField.getText());
    }//GEN-LAST:event_defineDateRadioButtonActionPerformed

    private void anyDateRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anyDateRadioButtonActionPerformed
        filterViewer.setDateFrom("");
        filterViewer.setDateTo("");
    }//GEN-LAST:event_anyDateRadioButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton anyDateRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton defineDateRadioButton;
    private javax.swing.JRadioButton definedCCsRadioButton;
    private javax.swing.JTextField definedCCsTextField;
    private javax.swing.JTabbedPane displayTabbedPane;
    private javax.swing.JTextField fromDateTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea newLegalStatusTextArea;
    private javax.swing.JTextArea newPublicationsTextArea;
    private javax.swing.JTextArea pairBulkDataTextArea;
    private javax.swing.JTextField profileNameTextField;
    private javax.swing.JPanel profilesPanel;
    private javax.swing.JTextArea rawJsonTextArea;
    private javax.swing.JButton runPLMonitorButton;
    private javax.swing.JTabbedPane setupTabbedPane;
    private javax.swing.JTextField toDateTextField;
    private javax.swing.JRadioButton worldwideRadioButton;
    // End of variables declaration//GEN-END:variables
}
